/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WidgetRouteImport } from './routes/widget'
import { Route as DuelRouteImport } from './routes/duel'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomCodeRouteImport } from './routes/room.$code'
import { Route as DuelCodeRouteImport } from './routes/duel.$code'
import { Route as AuthenticatedRouletteIrlRouteImport } from './routes/_authenticated/roulette-irl'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedPenseesRouteImport } from './routes/_authenticated/pensees'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedHubRouteImport } from './routes/_authenticated/hub'

const WidgetRoute = WidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelRoute = DuelRouteImport.update({
  id: '/duel',
  path: '/duel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomCodeRoute = RoomCodeRouteImport.update({
  id: '/room/$code',
  path: '/room/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelCodeRoute = DuelCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => DuelRoute,
} as any)
const AuthenticatedRouletteIrlRoute =
  AuthenticatedRouletteIrlRouteImport.update({
    id: '/roulette-irl',
    path: '/roulette-irl',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPenseesRoute = AuthenticatedPenseesRouteImport.update({
  id: '/pensees',
  path: '/pensees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHubRoute = AuthenticatedHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/duel': typeof DuelRouteWithChildren
  '/widget': typeof WidgetRoute
  '/hub': typeof AuthenticatedHubRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/pensees': typeof AuthenticatedPenseesRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/roulette-irl': typeof AuthenticatedRouletteIrlRoute
  '/duel/$code': typeof DuelCodeRoute
  '/room/$code': typeof RoomCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/duel': typeof DuelRouteWithChildren
  '/widget': typeof WidgetRoute
  '/hub': typeof AuthenticatedHubRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/pensees': typeof AuthenticatedPenseesRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/roulette-irl': typeof AuthenticatedRouletteIrlRoute
  '/duel/$code': typeof DuelCodeRoute
  '/room/$code': typeof RoomCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/duel': typeof DuelRouteWithChildren
  '/widget': typeof WidgetRoute
  '/_authenticated/hub': typeof AuthenticatedHubRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/pensees': typeof AuthenticatedPenseesRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/roulette-irl': typeof AuthenticatedRouletteIrlRoute
  '/duel/$code': typeof DuelCodeRoute
  '/room/$code': typeof RoomCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/duel'
    | '/widget'
    | '/hub'
    | '/messages'
    | '/pensees'
    | '/profil'
    | '/roulette-irl'
    | '/duel/$code'
    | '/room/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/duel'
    | '/widget'
    | '/hub'
    | '/messages'
    | '/pensees'
    | '/profil'
    | '/roulette-irl'
    | '/duel/$code'
    | '/room/$code'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/duel'
    | '/widget'
    | '/_authenticated/hub'
    | '/_authenticated/messages'
    | '/_authenticated/pensees'
    | '/_authenticated/profil'
    | '/_authenticated/roulette-irl'
    | '/duel/$code'
    | '/room/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DuelRoute: typeof DuelRouteWithChildren
  WidgetRoute: typeof WidgetRoute
  RoomCodeRoute: typeof RoomCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/widget': {
      id: '/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof WidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duel': {
      id: '/duel'
      path: '/duel'
      fullPath: '/duel'
      preLoaderRoute: typeof DuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$code': {
      id: '/room/$code'
      path: '/room/$code'
      fullPath: '/room/$code'
      preLoaderRoute: typeof RoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duel/$code': {
      id: '/duel/$code'
      path: '/$code'
      fullPath: '/duel/$code'
      preLoaderRoute: typeof DuelCodeRouteImport
      parentRoute: typeof DuelRoute
    }
    '/_authenticated/roulette-irl': {
      id: '/_authenticated/roulette-irl'
      path: '/roulette-irl'
      fullPath: '/roulette-irl'
      preLoaderRoute: typeof AuthenticatedRouletteIrlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pensees': {
      id: '/_authenticated/pensees'
      path: '/pensees'
      fullPath: '/pensees'
      preLoaderRoute: typeof AuthenticatedPenseesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hub': {
      id: '/_authenticated/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AuthenticatedHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHubRoute: typeof AuthenticatedHubRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedPenseesRoute: typeof AuthenticatedPenseesRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedRouletteIrlRoute: typeof AuthenticatedRouletteIrlRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHubRoute: AuthenticatedHubRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedPenseesRoute: AuthenticatedPenseesRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedRouletteIrlRoute: AuthenticatedRouletteIrlRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DuelRouteChildren {
  DuelCodeRoute: typeof DuelCodeRoute
}

const DuelRouteChildren: DuelRouteChildren = {
  DuelCodeRoute: DuelCodeRoute,
}

const DuelRouteWithChildren = DuelRoute._addFileChildren(DuelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DuelRoute: DuelRouteWithChildren,
  WidgetRoute: WidgetRoute,
  RoomCodeRoute: RoomCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
